GuiStyle = {}
GuiStyle.Colors = {}

GuiStyle.Colors.Text = 0
GuiStyle.Colors.TextDisabled = 1
GuiStyle.Colors.WindowBg = 2
GuiStyle.Colors.ChildWindowBg = 3
GuiStyle.Colors.PopupBg = 4
GuiStyle.Colors.Border = 5
GuiStyle.Colors.BorderShadow = 6
GuiStyle.Colors.FrameBg = 7
GuiStyle.Colors.FrameBgHovered = 8
GuiStyle.Colors.FrameBgActive = 9
GuiStyle.Colors.TitleBg = 10
GuiStyle.Colors.TitleBgCollapsed = 11
GuiStyle.Colors.TitleBgActive = 12
GuiStyle.Colors.MenuBarBg = 13
GuiStyle.Colors.ScrollbarBg = 14
GuiStyle.Colors.ScrollbarGrab = 15
GuiStyle.Colors.ScrollbarGrabHovered = 16
GuiStyle.Colors.ScrollbarGrabActive = 17
GuiStyle.Colors.ComboBg = 18
GuiStyle.Colors.CheckMark = 19
GuiStyle.Colors.SliderGrab = 20
GuiStyle.Colors.SliderGrabActive = 21
GuiStyle.Colors.Button = 22
GuiStyle.Colors.ButtonHovered = 23
GuiStyle.Colors.ButtonActive = 24
GuiStyle.Colors.Header = 25
GuiStyle.Colors.HeaderHovered = 26
GuiStyle.Colors.HeaderActive = 27
GuiStyle.Colors.Column = 28
GuiStyle.Colors.ColumnHovered = 29
GuiStyle.Colors.ColumnActive = 30
GuiStyle.Colors.ResizeGrip = 31
GuiStyle.Colors.ResizeGripHovered = 32
GuiStyle.Colors.ResizeGripActive = 33
GuiStyle.Colors.CloseButton = 34
GuiStyle.Colors.CloseButtonHovered = 35
GuiStyle.Colors.CloseButtonActive = 36
GuiStyle.Colors.PlotLines = 37
GuiStyle.Colors.PlotLinesHovered = 38
GuiStyle.Colors.PlotHistogram = 39
GuiStyle.Colors.PlotHistogramHovered = 40
GuiStyle.Colors.TextSelectedBg = 41
GuiStyle.Colors.ModalWindowDarkening = 42

GuiStyle.Var = {}
GuiStyle.Var.Alpha                = 0 -- float
GuiStyle.Var.WindowPadding        = 1 -- vec2
GuiStyle.Var.WindowRounding       = 2 -- float
GuiStyle.Var.WindowMinSize        = 3 -- vec2
GuiStyle.Var.ChildWindowRounding  = 4 -- float
GuiStyle.Var.FramePadding         = 5 -- vec2
GuiStyle.Var.FrameRounding        = 6 -- float
GuiStyle.Var.ItemSpacing          = 7 -- vec2
GuiStyle.Var.ItemInnerSpacing     = 8 -- vec2
GuiStyle.Var.IndentSpacing        = 9 -- float
GuiStyle.Var.GrabMinSize          = 10 -- float

GuiStyle.Var.WindowTitleAlign = 0 -- vec2
GuiStyle.Var.ScrollbarSize = 1 -- float
GuiStyle.Var.ScrollbarRounding = 2 -- float

GuiStyle.WindowFlags = {}
GuiStyle.WindowFlags.NoTitleBar = "NoTitleBar"
GuiStyle.WindowFlags.NoResize = "NoResize"
GuiStyle.WindowFlags.NoMove = "NoMove"
GuiStyle.WindowFlags.NoScrollbar = "NoScrollbar"
GuiStyle.WindowFlags.NoScrollWithMouse = "NoScrollWithMouse"
GuiStyle.WindowFlags.NoCollapse = "NoCollapse"
GuiStyle.WindowFlags.AlwaysAutoResize = "AlwaysAutoResize"
GuiStyle.WindowFlags.ShowBorders = "ShowBorders"
GuiStyle.WindowFlags.NoSavedSettings = "NoSavedSettings"
GuiStyle.WindowFlags.NoInputs = "NoInputs"
GuiStyle.WindowFlags.MenuBar = "MenuBar"
GuiStyle.WindowFlags.HorizontalScrollbar = "HorizontalScrollbar"
GuiStyle.WindowFlags.NoFocusOnAppearing = "NoFocusOnAppearing"
GuiStyle.WindowFlags.AlwaysVerticalScrollbar = "AlwaysVerticalScrollbar"
GuiStyle.WindowFlags.AlwaysHorizontalScrollbar = "AlwaysHorizontalScrollbar"
GuiStyle.WindowFlags.AlwaysUseWindowPadding = "AlwaysUseWindowPadding"


